### PR TITLE
Add multilevel wildcard support

### PR DESCRIPTION
**Pull request by tjheiska**
Hi. If you don't mind I would also like to suggest this patch to add feature allowing developer to subscribe topics ending with multilevel wildcard (#). Also fixed the pom.xml so that maven will actually run the tests I added support last time.

### CODE REVIEW

**Comment by tocrhz** [comment]
Greate, thankyou! But i think it's better to modify it here. 
```java
    private static String replaceSymbols(String topic) {
        StringBuilder sb = new StringBuilder();
            ...
                case '+':
                    sb.append("[^/]+");
                    break;
+               case '#':
+                  sb.append(".*");
+                  break;
                default:
                    sb.append(ch);
            }
        }
-      return sb.toString().replaceAll("/#$", "/.*");
+      return sb.toString();
    }
```

**Comment by tjheiska** [comment]
> Greate, thankyou! But i think it's better to modify it here.
> 
> ```java
>     private static String replaceSymbols(String topic) {
>         StringBuilder sb = new StringBuilder();
>             ...
>                 case '+':
>                     sb.append("[^/]+");
>                     break;
> +               case '#':
> +                  sb.append(".*");
> +                  break;
>                 default:
>                     sb.append(ch);
>             }
>         }
> -      return sb.toString().replaceAll("/#$", "/.*");
> +      return sb.toString();
>     }
> ```

Can do like that also, but I think it was more correct with replaceAll, since # only works as wildcard if it's alone or the topic ends with /#. Would have needed to change the loop more to code that in.

**Comment by tocrhz** [comment]
topic is verified on line 45 use `MqttTopic.validate()`, so if it doesn't conform to the specification, it will throw an exception.

**Comment by tocrhz** [comment]
topic is verified on line 45 use `MqttTopic.validate()`, so if it doesn't conform to the specification, it will throw an exception.

**Comment by tjheiska** [comment]
Ah, sorry. Missed that. Then definitely, it's the best now. Thank you!

**Pull request merged**
